### PR TITLE
Fix double &amp encoding

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @JordanMilne 

This takes care of issues like:

screen shot 2015-03-30 at 11 50 04 am

### CODE REVIEW

**Comment by btholt** [comment]
fish gif
:fish:

**Comment by JordanMilne** [comment]
This won't fix the real issue. All the data coming from reddit's API is always HTML-escaped, no matter what the data actually is. You'll probably see similar issues if you do `<http://example.com/autolink>`.

That means that if someone puts `&nbsp;` in their comment, it gets sent out as `&amp;nbsp;`. This needs to be fixed in whatever lib we're using to talk to the API.

**Comment by JordanMilne** [comment]
:nail_care: to clean up my salon

**Comment by JordanMilne** [comment]
Is this still an issue since the changes in snoode?

**Pull request closed without merging**
